upload:
  volume: /chatop-api/src/main/resources/static/images/

server:
  port : 8082

spring:
  web:
    resources:
      static-locations: 'file:/chatop-api/src/main/resources/static/images/'
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_chatop
    username: root
    password: ${mysql-root-pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:secrets.properties
application:
  security:
    jwt:
      secret-key: ${jwt-secret-pass}
      expiration: 8640000
