version: '3.8'
services:
  mysql_server:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-pass
      MYSQL_USER: dba
      MYSQL_DATABASE: db_chatop
    secrets:
      - mysql-root-pass
    networks:
      - adminer-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql_server
    depends_on:
      - mysql_server
    networks:
      - adminer-network
volumes:
  mysql-data:

networks:
  adminer-network:

secrets:
  mysql-root-pass:
    external: true